
repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.3.0
        hooks:
        -   id: check-yaml
            args: [--allow-multiple-documents]
        -   id: end-of-file-fixer
        -   id: trailing-whitespace
    -   repo: https://github.com/pycqa/isort
        rev: 5.8.0
        hooks:
        - id: isort
          args: ["--profile", "black", "--filter-files"]
    -   repo: https://github.com/psf/black
        rev: 21.5b1
        hooks:
        - id: black
    -   repo: https://gitlab.com/pycqa/flake8
        rev: 3.8.3
        hooks:
        - id: flake8
          args: ['--ignore=F401,W503', '--max-line-length=88']
